name = "uptime-xat"
main = "worker.js"
compatibility_date = "2024-05-01"

[[kv_namespaces]]
binding = "UPTIME_KV"
id = "9baf76e513f24bceb6800857b8a34f58"
preview_id = "9baf76e513f24bceb6800857b8a34f58"
